#!/usr/bin/env bun
/*
 * wiki-check.mjs — deterministic drift detector for project-wiki/.
 *
 * The wiki is semantic prose, so it cannot be auto-regenerated by a script.
 * What a script CAN do is DETECT drift and tell a human/agent which pages need
 * attention. Repair is done by an
 * agent following project-wiki/WIKI.md (the ingest/lint protocol).
 *
 * Modes:
 *   bun scripts/wiki-check.mjs            Full audit. Exit 1 if any page is stale
 *                                         or cites a missing source (CI-friendly).
 *   bun scripts/wiki-check.mjs --staged   Pre-commit mode: list wiki pages whose
 *                                         `sources:` include a STAGED changed file.
 *                                         Always exits 0 (non-blocking nudge).
 *   bun scripts/wiki-check.mjs --mark     During audit, set `status: stale` on
 *                                         drifted pages and append a log.md entry.
 *
 * A page is "stale" when any file in its frontmatter `sources:` has a git commit
 * newer than the page's `verified_at` date.
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync, appendFileSync } from "node:fs";
import { join, basename, relative } from "node:path";
import { execSync } from "node:child_process";

const ROOT = process.cwd();
const WIKI = join(ROOT, "project-wiki");
// Structural pages that are not anchored to source files:
const NON_SOURCE_PAGES = new Set(["WIKI.md", "index.md", "log.md"]);

const args = new Set(process.argv.slice(2));
const STAGED = args.has("--staged");
const MARK = args.has("--mark");

if (!existsSync(WIKI)) {
  console.error("project-wiki/ not found — run from the repo root.");
  process.exit(2);
}

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (entry.endsWith(".md")) out.push(p);
  }
  return out;
}

function git(cmd) {
  try {
    return execSync(`git ${cmd}`, { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}

// Strip fenced code blocks and inline code so illustrative `[[example]]` links
// inside code samples (in WIKI.md, glossary.md, etc.) aren't mistaken for live
// wikilinks. Fenced blocks are removed before inline code so backticks inside a
// fence don't confuse the inline pass.
function stripCode(md) {
  return md
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`[^`\n]*`/g, "");
}

// Pull the `---` frontmatter block and extract sources/verified_at/status.
function parseFrontmatter(text) {
  if (!text.startsWith("---")) return null;
  const end = text.indexOf("\n---", 3);
  if (end === -1) return null;
  const block = text.slice(3, end);
  const lines = block.split("\n");

  const get = (key) => {
    const re = new RegExp(`^${key}:\\s*(.*)$`);
    for (const l of lines) {
      const m = l.match(re);
      if (m) return m[1].trim();
    }
    return "";
  };

  // sources: either inline `[a, b]` or a following block list of `  - path`
  let sources = [];
  const inline = get("sources");
  if (inline.startsWith("[")) {
    sources = inline.replace(/^\[|\]$/g, "").split(",").map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
  } else {
    const idx = lines.findIndex((l) => /^sources:\s*$/.test(l));
    if (idx !== -1) {
      for (let i = idx + 1; i < lines.length; i++) {
        const m = lines[i].match(/^\s+-\s+(.+)$/);
        if (!m) break;
        sources.push(m[1].trim().replace(/^["']|["']$/g, ""));
      }
    }
  }
  return { verified_at: get("verified_at"), status: get("status"), sources };
}

const pages = walk(WIKI);
const slugSet = new Set(pages.map((p) => basename(p, ".md")));
const indexText = existsSync(join(WIKI, "index.md")) ? readFileSync(join(WIKI, "index.md"), "utf8") : "";

// ── --staged mode: which pages reference a staged-changed code file? ──────────
if (STAGED) {
  const changed = git("diff --cached --name-only --diff-filter=ACMR")
    .split("\n").map((s) => s.trim()).filter(Boolean);
  if (changed.length === 0) process.exit(0);
  const changedSet = new Set(changed);
  const hits = [];
  for (const page of pages) {
    if (NON_SOURCE_PAGES.has(basename(page))) continue;
    const fm = parseFrontmatter(readFileSync(page, "utf8"));
    if (!fm) continue;
    const touched = fm.sources.filter((s) => changedSet.has(s.replace(/\\/g, "/")));
    if (touched.length) hits.push({ page: relative(ROOT, page), touched });
  }
  if (hits.length) {
    console.log("\n📝 project-wiki: you changed code that these wiki pages document —");
    console.log("   review/update them and bump `verified_at` (the wiki is repaired by an agent, see project-wiki/WIKI.md):");
    for (const h of hits) console.log(`   • ${h.page}  ←  ${h.touched.join(", ")}`);
    console.log("");
  }
  process.exit(0); // never block a commit
}

// ── full audit ───────────────────────────────────────────────────────────────
const missingSources = [];
const stale = [];
const orphans = [];
const brokenLinks = [];

for (const page of pages) {
  const rel = relative(ROOT, page);
  const text = readFileSync(page, "utf8");
  const name = basename(page);

  // broken wikilinks (warn only — WIKI.md allows links to not-yet-written pages,
  // but a link whose slug differs from every page is likely a typo). Code-span
  // examples are skipped (stripCode), and `#anchor` suffixes are resolved: a pure
  // `[[#section]]` is a same-page anchor (always valid); `[[page#section]]`
  // validates the page part only.
  for (const m of stripCode(text).matchAll(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g)) {
    const target = m[1].trim();
    const slug = target.split("#")[0].trim();
    if (slug === "") continue; // same-page anchor link
    if (!slugSet.has(slug)) brokenLinks.push({ page: rel, slug: target });
  }

  if (NON_SOURCE_PAGES.has(name)) continue;

  // orphan: not catalogued in index.md
  if (indexText && !indexText.includes(`[[${basename(page, ".md")}]]`)) {
    orphans.push(rel);
  }

  const fm = parseFrontmatter(text);
  if (!fm) continue;

  for (const src of fm.sources) {
    if (!existsSync(join(ROOT, src))) missingSources.push({ page: rel, src });
  }

  // staleness: any source committed after verified_at
  if (fm.verified_at) {
    const cutoff = new Date(`${fm.verified_at}T23:59:59`);
    for (const src of fm.sources) {
      if (!existsSync(join(ROOT, src))) continue;
      const iso = git(`log -1 --format=%cI -- "${src}"`);
      if (iso && new Date(iso) > cutoff) {
        stale.push({ page: rel, src, committed: iso.slice(0, 10), verified: fm.verified_at });
        break;
      }
    }
  }
}

const report = (title, items, fmt) => {
  if (!items.length) return;
  console.log(`\n${title} (${items.length}):`);
  for (const it of items) console.log(`   ${fmt(it)}`);
};

report("❌ MISSING SOURCES (cited file does not exist)", missingSources, (i) => `${i.page}  →  ${i.src}`);
report("⚠️  STALE (source changed after verified_at)", stale, (i) => `${i.page}  ←  ${i.src} committed ${i.committed} > verified ${i.verified}`);
report("🔗 BROKEN WIKILINKS (slug matches no page — possible typo)", brokenLinks, (i) => `${i.page}  →  [[${i.slug}]]`);
report("👻 ORPHAN PAGES (not in index.md)", orphans, (p) => p);

if (MARK && stale.length) {
  for (const { page } of stale) {
    const abs = join(ROOT, page);
    const t = readFileSync(abs, "utf8").replace(/^(status:\s*)\w+/m, "$1stale");
    writeFileSync(abs, t);
  }
  const day = new Date().toISOString().slice(0, 10);
  appendFileSync(join(WIKI, "log.md"),
    `\n## [${day}] lint | ${stale.length} page(s) | marked stale (source changed after verified_at): ${stale.map((s) => basename(s.page, ".md")).join(", ")}\n`);
  console.log(`\n🖊️  Marked ${stale.length} page(s) status: stale and logged to project-wiki/log.md`);
}

const errors = missingSources.length + stale.length;
if (errors === 0) {
  console.log("✅ project-wiki: no missing sources, no stale pages.");
}
process.exit(errors > 0 ? 1 : 0);
